workflows:

  # Run this workflow ONCE first to generate native iOS/Android files
  # and commit them to the repo.
  # Prerequisite: add GITHUB_TOKEN (repo-scoped PAT) in
  # Codemagic > your app > Environment variables.
  setup-native-files:
    name: "SETUP (run once) - Generate native project files"
    max_build_duration: 20

    environment:
      flutter: stable
      groups:
        - secrets

    scripts:
      - name: Generate iOS and Android native project structure
        script: |
          set -e
          flutter create \
            --org com.rescydris \
            --project-name loop_timer \
            .
          echo "=== iOS ==="
          ls ios/
          echo "=== Android ==="
          ls android/

      - name: Add background audio to Info.plist
        script: |
          set -e
          /usr/libexec/PlistBuddy \
            -c "Add :UIBackgroundModes array" \
            ios/Runner/Info.plist
          /usr/libexec/PlistBuddy \
            -c "Add :UIBackgroundModes:0 string audio" \
            ios/Runner/Info.plist
          echo "UIBackgroundModes:audio added"

      - name: Commit and push native files to repository
        script: |
          set -e
          git config user.email "jonahwilliams95@gmail.com"
          git config user.name "Jonah Williams"
          git add ios/ android/
          echo "=== Staged files ==="
          git status

          # Store credentials via helper so the token is not embedded in the URL
          git config --global credential.helper store
          printf "https://res-cydris:%s@github.com\n" "${GITHUB_TOKEN}" \
            > ~/.git-credentials

          # Ensure the remote points to a plain HTTPS URL
          git remote set-url origin "https://github.com/res-cydris/loop-timer.git"

          git commit -m "Add generated native iOS and Android project files"
          git push origin HEAD:main
          echo "Done - native files committed to repository."

  # Regular iOS build - run this after setup-native-files has run once.
  ios-adhoc:
    name: "Loop Timer - iOS Ad Hoc"
    max_build_duration: 60

    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.rescydris.looptimer
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          set -e
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          set -e
          cd ios && pod install

      - name: Build iOS IPA
        script: |
          set -e
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - jonahwilliams95@gmail.com
        notify:
          success: true
          failure: true
